### ISSUE TITLE
LayoutSwitcher don’t open

### ISSUE THREAD

**Issue by RonFahima** [3t0n/LayoutSwitcher#2]
Hi, 3t0n. First, thank you for the app. It is good.  
I just updated my macOS to 13, and it did not open. Try many ways, but unfortunately, it didn't work 
Maybe you know why it won't work on macOS 13?

**Comment by abdullahTreesal** [comment]
same issue

**Comment by 3t0n** [comment]
I rebuild the app (v.1.2.0) for Mac OS Ventura (13.0). Please check how it works:
https://github.com/3t0n/LayoutSwitcher/releases/tag/v.1.2.0

**Comment by abdullahTreesal** [comment]
I just downloaded the latest version but still, it doesn't open at all nothing appears in the menu bar.

**Comment by 3t0n** [comment]
Did you provide access rights to the application in settings?
<img width="998" alt="Screenshot 2022-10-28 at 11 09 50" src="https://user-images.githubusercontent.com/3111133/198538007-670254f1-d242-4bbe-bd58-2fa858309f88.png">

**Comment by ghost** [comment]
Hey @3t0n,
First of all thank you so much for creating this project it made my life much better!
When trying to open it shows this error.
![image](https://user-images.githubusercontent.com/49374103/198886655-fb94757d-e493-4815-b2a4-5532a38064fc.png)

**Comment by abdullahTreesal** [comment]
> Did you provide access rights to the application in settings?
> <img alt="Screenshot 2022-10-28 at 11 09 50" width="998" src="https://user-images.githubusercontent.com/3111133/198538007-670254f1-d242-4bbe-bd58-2fa858309f88.png">

yes I Did

**Comment by Perforator04** [comment]
Hello, same issue.  Work great before updating. now on Ventura 13.0 (22A380) doe'snt open.

**Comment by Maghsad** [comment]
Hi @3t0n ,
Thanks for your practical app. Same as others, it worked before upgrading to macOS Ventura 13.0. Now, it does not open.

Version 1.0 and 1.2 were tested and none of them opens. 
Even re-installing the app and giving access again does not help.

<a href="https://ibb.co/CHRgtP1"><img src="https://i.ibb.co/sV8nPWm/Layout-Switcher.png" alt="Layout-Switcher" border="0"></a>

**Comment by Maghsad** [comment]
@3t0n Any updates?

**Comment by 3t0n** [comment]
Sorry guys, no time to investigate this issue this week. Hope will have some time next week.

**Comment by 3t0n** [comment]
Seems Apple removed “Allow applications downloaded from anywhere” option from the settings:
https://osxdaily.com/2022/11/17/allow-apps-downloaded-open-anywhere-macos/ 

You can enable it again using Terminal: sudo spctl --master-disable
That will fix the message you post above :)

**Comment by 3t0n** [comment]
There is also another issue: https://github.com/3t0n/LayoutSwitcher/issues/4#issue-1460375906 
So I'm going to update the documentation and fix this new issue
